import { Step } from 'react-joyride';

import { WorldCreationStartTooltip } from '@/components/TutorialProvider/WorldCreationStartTooltip';

export const worldCreationTour: Step[] = [
  {
    target: '[data-tutorial="world-type-selector"]',
    content: 'Welcome to the World Creation Wizard! Choose a path: start from scratch on the left, or use a template on the right.',
    placement: 'top',
    tooltipComponent: WorldCreationStartTooltip,
    disableBeacon: true,
  },
  {
    target: '[data-tutorial="create-own-world-btn"]',
    content: 'Start from scratch with Create My Own World and define everything yourself.',
    placement: 'top',
    tooltipComponent: WorldCreationStartTooltip,
    disableBeacon: true,
  },
  {
    target: '[data-tutorial="template-list"]',
    content: 'Use a template to jump-start your world with a curated setup.',
    placement: 'top',
    tooltipComponent: WorldCreationStartTooltip,
    disableBeacon: true,
  },
  {
    target: '[data-tutorial="generate-tab"]',
    content: 'Switch to Generate to create a new template you can customize.',
    placement: 'top',
    tooltipComponent: WorldCreationStartTooltip,
    disableBeacon: true,
    data: { isEndOfPage: true },
  },
  {
    target: '[data-tutorial="world-name"]',
    content: 'Give your world a name so it feels distinct. This is optional, but it helps personalize your story.',
    placement: 'top',
    disableBeacon: true,
  },
  {
    target: '[data-tutorial="genre-picker"]',
    content: 'Select a genre to define the tone and available options for your world. This influences the storytelling style.',
    placement: 'top',
    disableBeacon: true,
  },
  {
    target: '[data-tutorial="world-type"]',
    content: 'Choose whether your world is original, inspired by an existing setting, or set within one.',
    placement: 'top',
    disableBeacon: true,
  },
  {
    target: '[data-tutorial="world-reference"]',
    content: 'If you chose Inspired By or Set Within, enter the setting you want the AI to follow.',
    placement: 'top',
    disableBeacon: true,
    data: { skipIfMissing: true },
  },
  {
    target: '[data-tutorial="tone-content-rating"]',
    content: 'Set the content rating to match the audience and intensity you want.',
    placement: 'top',
    disableBeacon: true,
  },
  {
    target: '[data-tutorial="tone-narrative-style"]',
    content: 'Pick the narrative style that fits your world, from cinematic to conversational.',
    placement: 'top',
    disableBeacon: true,
  },
  {
    target: '[data-tutorial="tone-language-complexity"]',
    content: 'Adjust language complexity to match the reading level you want.',
    placement: 'top',
    disableBeacon: true,
  },
  {
    target: '[data-tutorial="tone-custom-instructions"]',
    content: 'Add any extra tone or style guidance you want the AI to follow.',
    placement: 'top',
    disableBeacon: true,
    data: { isEndOfPage: true },
  },
  {
    target: '[data-tutorial="world-description"]',
    content: 'Describe your world in detail. This will be used to generate rich lore, locations, and history.',
    placement: 'top',
    disableBeacon: true,
  },
  {
    target: '[data-tutorial="ai-suggestions-actions"]',
    content: 'Generate suggestions to see sample attributes and skills tailored to your description.',
    placement: 'top',
    disableBeacon: true,
  },
  {
    target: '[data-tutorial="ai-suggestions-preview"]',
    content: 'Preview the suggested attributes and skills before you review them in detail.',
    placement: 'top',
    disableBeacon: true,
    data: { isEndOfPage: true },
  },
  {
    target: '[data-tutorial="attribute-editor"]',
    content: 'Review and customize the core attributes that define characters in your world.',
    placement: 'top',
    disableBeacon: true,
  },
  {
    target: '[data-tutorial="attribute-suggestions"]',
    content: 'Use the suggested attributes as-is or customize them to fit your world.',
    placement: 'top',
    disableBeacon: true,
  },
  {
    target: '[data-tutorial="attribute-custom"]',
    content: 'Add custom attributes if you want something unique to your setting.',
    placement: 'top',
    disableBeacon: true,
  },
  {
    target: '[data-tutorial="attribute-summary"]',
    content: 'Keep an eye on how many attribute slots you have left.',
    placement: 'top',
    disableBeacon: true,
    data: { isEndOfPage: true },
  },
  {
    target: '[data-tutorial="skill-editor"]',
    content: 'Define the skills characters can learn. These are based on the genre and attributes you selected.',
    placement: 'top',
    disableBeacon: true,
  },
  {
    target: '[data-tutorial="skill-suggestions"]',
    content: 'Review the suggested skills and tweak them to match your world.',
    placement: 'top',
    disableBeacon: true,
  },
  {
    target: '[data-tutorial="skill-custom"]',
    content: 'Create custom skills to round out your world\'s possibilities.',
    placement: 'top',
    disableBeacon: true,
  },
  {
    target: '[data-tutorial="skill-summary"]',
    content: 'Track how many skills you have selected as you refine the list.',
    placement: 'top',
    disableBeacon: true,
    data: { isEndOfPage: true },
  },
  {
    target: '[data-tutorial="finalize-review"]',
    content: 'Review the core world details before you finalize.',
    placement: 'top',
    disableBeacon: true,
  },
  {
    target: '[data-tutorial="finalize-image"]',
    content: 'Generate or update the world image to match your setting.',
    placement: 'top',
    disableBeacon: true,
  },
  {
    target: '[data-tutorial="finalize-attributes"]',
    content: 'Double-check the attributes you\'ve chosen.',
    placement: 'top',
    disableBeacon: true,
  },
  {
    target: '[data-tutorial="finalize-skills"]',
    content: 'Confirm the skills list before creating the world.',
    placement: 'top',
    disableBeacon: true,
  },
  {
    target: '[data-tutorial="finalize-world"]',
    content: 'Review your world details and create it! You\'re just one step away from your adventure.',
    placement: 'top',
    disableBeacon: true,
  },
];

export const tourStepToWizardStep: Record<number, number> = {
  0: 0,
  1: 0,
  2: 0,
  3: 0,
  4: 1,
  5: 1,
  6: 1,
  7: 1,
  8: 1,
  9: 1,
  10: 1,
  11: 1,
  12: 2,
  13: 2,
  14: 2,
  15: 3,
  16: 3,
  17: 3,
  18: 3,
  19: 4,
  20: 4,
  21: 4,
  22: 4,
  23: 5,
  24: 5,
  25: 5,
  26: 5,
  27: 5,
};
