flowchart LR

subgraph 0["src"]
subgraph 1["components"]
2["CharacterCard"]
3["CharacterCreationWizard"]
4["CharacterEditor"]
5["CharacterPortrait"]
6["ClientOnlyDevTools.tsx"]
7["ConfirmationDialog"]
8["DeleteConfirmationDialog"]
9["GameSession"]
A["GameStartWizard"]
B["GenerateCharacterDialog"]
C["GuidedFirstTimeExperience"]
D["Journal"]
E["LoreViewer"]
F["Narrative"]
G["Navigation"]
H["QuickPlay"]
I["QuickStartCharacters"]
J["StoryEndingDialog"]
K["WorldCard"]
L["WorldCreationWizard"]
M["WorldEditor"]
N["WorldImage"]
O["WorldList"]
P["WorldListScreen"]
Q["character"]
R["characters"]
S["devtools"]
T["forms"]
U["inventory"]
V["shared"]
W["ui"]
X["world"]
end
end
2-->5
2-->V
2-->W
3-->V
3-->W
3-->5
4-->8
4-->W
4-->5
4-->V
6-->S
7-->V
7-->W
8-->V
8-->W
9-->W
9-->7
9-->U
9-->F
9-->V
9-->5
A-->W
A-->K
B-->V
B-->W
C-->V
D-->W
D-->V
F-->W
F-->S
G-->W
G-->V
H-->5
H-->8
H-->C
H-->V
H-->W
I-->V
I-->W
J-->V
J-->W
K-->V
K-->W
L-->W
L-->7
L-->V
L-->T
L-->X
L-->N
L-->I
M-->T
M-->W
O-->K
P-->8
P-->W
P-->X
P-->O
Q-->5
Q-->W
R-->5
S-->W
S-->V
T-->W
T-->V
T-->8
T-->X
T-->N
U-->W
V-->W
V-->9
X-->8
X-->W
X-->V
