import type { SessionStore } from '@/types/game.types';

export function createMockSessionStore(
  overrides?: Partial<SessionStore>
): SessionStore {
  return {
    id: null,
    status: 'idle',
    currentSceneId: null,
    playerChoices: [],
    error: null,
    worldId: null,
    characterId: null,
    savedSessions: {},
    sessionLifecycle: {},
    templateHistory: [],
    autoSave: {
      enabled: true,
      status: 'idle',
      lastSaveTime: null,
      errorMessage: null,
      totalSaves: 0,
    },
    tutorialProgress: {
      phases: {
        intro: { completed: false, skipped: false },
        worldCreation: { completed: false, skipped: false, lastStep: 0 },
        characterCreation: { completed: false, skipped: false, lastStep: 0 },
        firstPlay: { completed: false, skipped: false },
      },
      dismissedHints: [],
      lastActiveStep: null,
    },
    narrativeHeight: 400,
    initializeSession: jest.fn().mockResolvedValue(undefined),
    endSession: jest.fn(),
    setStatus: jest.fn(),
    setError: jest.fn(),
    setPlayerChoices: jest.fn(),
    selectChoice: jest.fn(),
    clearPlayerChoices: jest.fn(),
    setCurrentScene: jest.fn(),
    pauseSession: jest.fn(),
    resumeSession: jest.fn(),
    setSessionId: jest.fn(),
    setCharacterId: jest.fn(),
    getSavedSession: jest.fn(() => undefined),
    resumeSavedSession: jest.fn(() => false),
    deleteSavedSession: jest.fn(),
    updateSavedSessionNarrativeCount: jest.fn(),
    repairSavedSessionNarrativeCounts: jest.fn(),
    upsertSessionLifecycle: jest.fn(),
    setSessionLifecycleStatus: jest.fn(),
    getSessionLifecycle: jest.fn(() => undefined),
    addTemplateToHistory: jest.fn(),
    getTemplateHistory: jest.fn(() => []),
    clearTemplateHistory: jest.fn(),
    setAutoSaveEnabled: jest.fn(),
    updateAutoSaveStatus: jest.fn(),
    recordAutoSave: jest.fn(),
    updateTutorialProgress: jest.fn(),
    dismissTutorialHint: jest.fn(),
    resetTutorialProgress: jest.fn(),
    completeTutorialPhase: jest.fn(),
    getCurrentTutorialPhase: jest.fn(() => null),
    isTutorialComplete: jest.fn(() => false),
    shouldShowTutorialPhase: jest.fn(() => false),
    isFirstTimeUser: jest.fn(() => true),
    shouldShowOnboarding: jest.fn(() => false),
    ...overrides,
  } as SessionStore;
}
