'use client';

import React, { useState, useEffect, useCallback } from 'react';
import { World } from '@/types/world.types';
import { GeneratedImage } from '@/types/common.types';
import { wizardStyles, WizardFormSection } from '@/components/shared/wizard';
import { DataField } from '@/components/shared/DataField';
import { ImageGenerationSection } from '@/components/shared';
import { WorldImage as WorldImageComponent } from '@/components/WorldImage';
import { generateWorldImage } from '@/lib/ai/worldImageGenerator';
import { Button } from '@/components/ui/button';
import { getTimestamp } from '@/lib/utils';
import { getGenreLabel } from '@/lib/constants/genres';

import Logger from '@/lib/utils/logger';
const logger = new Logger('FinalizeStep');

interface FinalizeStepProps {
  worldData: Partial<World>;
  errors: Record<string, string>;
  onComplete: () => void;
  onBack?: () => void;
  onCancel?: () => void;
  onUpdateWorldData?: (updates: Partial<World>) => void;
}

export default function FinalizeStep({
  worldData,
  errors,
  onComplete,
  onBack,
  onCancel,
  onUpdateWorldData,
}: FinalizeStepProps) {
  const [isGeneratingImage, setIsGeneratingImage] = useState(false);
  const [hasAutoGenerated, setHasAutoGenerated] = useState(false);
  
  const log = (message: string, data?: unknown) => {
    logger.debug(message, data);
  };

  const handleGenerateImage = useCallback(async (customPrompt?: string) => {
    if (!onUpdateWorldData) return;
    
    setIsGeneratingImage(true);
    try {
      const tempWorld = {
        id: 'temp',
        name: worldData.name || 'Untitled World',
        description: worldData.description || '',
        genre: worldData.genre || 'fantasy',
        ...worldData
      } as World;

      const image = await generateWorldImage(tempWorld, customPrompt);
      onUpdateWorldData({ image });
    } catch (err) {
      logger.error('Failed to generate world image:', err);
      throw err;
    } finally {
      setIsGeneratingImage(false);
    }
  }, [onUpdateWorldData, worldData]);

  // Auto-generate world image when arriving on this step with AI-generated data
  useEffect(() => {
    const shouldAutoGenerate = 
      onUpdateWorldData && // Can update world data
      worldData.name && worldData.description && // Has required data
      !worldData.image?.url && // No image yet
      !hasAutoGenerated && // Haven't auto-generated yet
      !isGeneratingImage; // Not already generating

    if (shouldAutoGenerate) {
      setHasAutoGenerated(true);
      handleGenerateImage();
    }
  }, [worldData, onUpdateWorldData, hasAutoGenerated, isGeneratingImage, handleGenerateImage]);

  const handleRemoveImage = () => {
    if (!onUpdateWorldData) return;

    const placeholderImage: GeneratedImage = {
      type: 'placeholder',
      url: null,
      generatedAt: getTimestamp()
    };

    onUpdateWorldData({ image: placeholderImage });
  };

  const handleComplete = () => {
    log('[FinalizeStep.tsx - handleComplete] Button clicked, function entered.');
    if (onComplete) {
      log('[FinalizeStep.tsx - handleComplete] Calling onComplete prop.');
      onComplete();
    } else {
      log('[FinalizeStep.tsx - handleComplete] onComplete function is not provided');
      logger.error('[FinalizeStep.tsx - handleComplete] onComplete function is not provided');
    }
  };
  
  return (
    <div data-testid="finalize-step">
      <WizardFormSection
        title="Review Your World"
        description="Review your world configuration before creating it."
      >

      <div className="wizard-review-summary">
        <div data-tutorial="finalize-review">
          <h3 className={wizardStyles.subheading}>Basic Information</h3>
          <div className="wizard-review-fields">
            <DataField
              label="Name"
              value={<span data-testid="review-world-name">{worldData.name}</span>}
              variant="outline"
            />
            <DataField
              label="Genre"
              value={<span data-testid="review-world-genre">{worldData.genre ? getGenreLabel(worldData.genre) : 'Unknown'}</span>}
              variant="outline"
            />
            <DataField
              label="Description"
              value={<p data-testid="review-world-description">{worldData.description}</p>}
              variant="stacked"
            />
          </div>
        </div>

        {/* World Image Section */}
        <div
          className={`${wizardStyles.divider} wizard-image-section`}
          data-tutorial="finalize-image"
        >
          <h3 className={wizardStyles.subheading}>World Image</h3>
          {onUpdateWorldData ? (
            <ImageGenerationSection
              title=""
              description="Shown on world cards and as the hero image on the world details page."
              currentImageUrl={worldData.image?.url}
              currentImageType={worldData.image?.type}
              generatedAt={worldData.image?.generatedAt}
              currentPrompt={worldData.image?.prompt}
              isGenerating={isGeneratingImage}
              onGenerate={handleGenerateImage}
              onRemove={handleRemoveImage}
              customPromptLabel="Customize world image description"
              customPromptPlaceholder="Describe the specific visual elements you want in the world image (landscape, architecture, atmosphere, etc.)"
              customPromptHelpText="This will override the auto-generated prompt based on world details for this generation only"
              generateButtonText="Generate World Image"
              regenerateButtonText="Regenerate World Image"
              removeButtonText="Remove World Image"
              imageComponent={
                <WorldImageComponent
                  image={worldData.image || { type: 'placeholder', url: null }}
                  worldName={worldData.name || 'Untitled World'}
                  size="medium"
                />
              }
              
            />
          ) : (
            <div>
              <WorldImageComponent
                image={worldData.image || { type: 'placeholder', url: null }}
                worldName={worldData.name || 'Untitled World'}
                size="medium"
              />
              <p>
                {worldData.image?.url ? 'World image will be generated after creation' : 'No world image will be generated'}
              </p>
            </div>
          )}
        </div>

        <div className={wizardStyles.divider} data-testid="review-attributes-section" data-tutorial="finalize-attributes">
          <h3 className={wizardStyles.subheading}>Attributes ({worldData.attributes?.length || 0})</h3>
        {worldData.attributes && worldData.attributes.length > 0 ? (
          <div className="wizard-review-custom-list">
            {worldData.attributes.map((attr, index) => (
              <div key={index} className={`${wizardStyles.card.base} wizard-review-card`} data-testid={`review-attribute-${index}`}>
                <div className="wizard-review-card-meta">{attr.name}</div>
                <div className="wizard-review-card-detail">{attr.description}</div>
                <div className="wizard-review-card-range">
                  Range: {attr.minValue} - {attr.maxValue}
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div className="wizard-empty-state">
            <p>No attributes selected</p>
          </div>
        )}
        </div>

        <div className={wizardStyles.divider} data-testid="review-skills-section" data-tutorial="finalize-skills">
          <h3 className={wizardStyles.subheading}>Skills ({worldData.skills?.length || 0})</h3>
        {worldData.skills && worldData.skills.length > 0 ? (
          <div className="wizard-review-custom-list">
            {worldData.skills.map((skill, index) => (
              <div key={index} className={`${wizardStyles.card.base} wizard-review-card`} data-testid={`review-skill-${index}`}>
                <div className="wizard-review-card-meta">
                  <span>{skill.name}</span>
                  <span className={`${wizardStyles.badge.base} ${
                    skill.difficulty === 'easy' ? wizardStyles.badge.success :
                    skill.difficulty === 'medium' ? wizardStyles.badge.warning :
                    wizardStyles.badge.danger
                  }`}>
                    {skill.difficulty}
                  </span>
                </div>
                <div className="wizard-review-card-detail">{skill.description}</div>
                {skill.attributeIds && skill.attributeIds.length > 0 && (
                  <div className="wizard-review-card-range">
                    Linked to: {skill.attributeIds
                      .map(id => worldData.attributes?.find(a => a.id === id)?.name)
                      .filter(Boolean)
                      .join(', ') || 'Unknown'}
                  </div>
                )}
              </div>
            ))}
          </div>
        ) : (
          <div className="wizard-empty-state">
            <p>No skills selected</p>
          </div>
        )}
        </div>
      </div>
      </WizardFormSection>

      {errors.submit && (
        <div className={wizardStyles.errorContainer} data-testid="submit-error">
          {errors.submit}
        </div>
      )}

      <div className="wizard-button-row">
        <div className="wizard-nav-group">
          <Button
            type="button"
            onClick={onCancel || (() => window.history.back())}
            variant="outline"
          >
            Cancel
          </Button>

          {onBack && (
            <Button
              type="button"
              onClick={onBack}
              variant="outline"
            >
              Back
            </Button>
          )}
        </div>
        
        <Button
          type="button"
          data-testid="step-complete-button"
          data-tutorial="finalize-world"
          onClick={() => {
            log('[FinalizeStep.tsx - onClick] Button raw click detected.');
            handleComplete();
          }}
        >
          Create World
        </Button>
      </div>
    </div>
  );
}
