blank_issues_enabled: false
contact_links:
  - name: NarrAItor Documentation
    url: https://github.com/jerseycheese/narraitor/tree/main/docs
    about: Check the documentation for more information about the project.
