import { test, expect } from '@playwright/test';

/**
 * World detail NPCs section — single-theme (default DS1).
 *
 * DS coverage (#1264): this spec verifies NPC *content* (portrait images when
 * available, initials fallback when missing), not theme layout. The world detail
 * surface is covered across DS1/DS2/DS3 by tests/visual/world-detail-themes.spec.ts.
 */

/**
 * Frozen seed timestamp. This used to be getTimestamp() (i.e. "now"), which the
 * page prints back through WorldInfoSection's Created/Updated fields — so the
 * baseline baked in whatever day it was captured and drifted from every later
 * run. The DataFields are fixed-width, so the diff never reflowed the page and
 * stayed under maxDiffPixels; it was burning diff budget silently rather than
 * failing loudly.
 *
 * The value is the capture date of the committed baseline (last adopted in
 * #1660, from a CI run on 2026-08-04 UTC), so the frozen render still prints
 * "Aug 4, 2026" and matches it — no re-baseline needed. Noon UTC keeps the
 * formatted date a full 12 hours from a day boundary, so it can't roll over
 * even if a run somehow escapes the UTC pin in playwright.config.ts.
 */
const SEEDED_AT = '2026-08-04T12:00:00.000Z';
const WORLD_ID = 'world-npcs-playwright';
const NPC_WITH_PORTRAIT = 'npc-elara';
const NPC_NO_PORTRAIT = 'npc-thorgrim';

const SEED_PAYLOAD = {
  world: {
    id: WORLD_ID,
    name: 'Test Fantasy World',
    description: 'A world for testing NPC portrait displays',
    genre: 'fantasy',
  },
  npcs: [
    {
      id: NPC_WITH_PORTRAIT,
      name: 'Elara Moonwhisper',
      description: 'A mysterious elven ranger with silver hair',
      // Mock avatar URL (would be generated by portrait service in production)
      avatarUrl: 'https://api.dicebear.com/7.x/avataaars/svg?seed=elara',
    },
    {
      id: NPC_NO_PORTRAIT,
      name: 'Thorgrim Ironforge',
      description: 'A gruff dwarven blacksmith',
      // No avatarUrl - should show initials
      avatarUrl: undefined,
    },
  ],
};

test.describe('World details NPC portraits', () => {
  test('shows NPC portraits when available and initials fallback when not', async ({
    page,
    baseURL,
  }) => {
    await page.addInitScript(
      async ({ now, seed }) => {
        const dbName = 'narraitor-state';
        const storeName = 'narraitor-store';

        function put(key: string, value: unknown): Promise<void> {
          return new Promise((resolve) => {
            const open = indexedDB.open(dbName, 1);
            open.onupgradeneeded = () => {
              const db = open.result;
              if (!db.objectStoreNames.contains(storeName)) {
                db.createObjectStore(storeName);
              }
            };
            open.onsuccess = () => {
              const db = open.result;
              const tx = db.transaction(storeName, 'readwrite');
              tx.objectStore(storeName).put({ id: key, value }, key);
              tx.oncomplete = () => resolve();
              tx.onerror = () => resolve();
            };
            open.onerror = () => resolve();
          });
        }

        const worldPersist = {
          state: {
            worlds: {
              [seed.world.id]: {
                ...seed.world,
                attributes: [],
                skills: [],
                derivedStats: [],
                settings: {
                  maxAttributes: 6,
                  maxSkills: 10,
                  attributePointPool: 27,
                  skillPointPool: 40,
                },
                createdAt: now,
                updatedAt: now,
              },
            },
            entities: {
              [seed.world.id]: {
                ...seed.world,
                attributes: [],
                skills: [],
                derivedStats: [],
                settings: {
                  maxAttributes: 6,
                  maxSkills: 10,
                  attributePointPool: 27,
                  skillPointPool: 40,
                },
                createdAt: now,
                updatedAt: now,
              },
            },
            worldStates: {
              [seed.world.id]: {
                worldId: seed.world.id,
                version: 1,
                lastModified: now,
                npcRelationships: {},
                majorEvents: [],
                playerCharacterThreads: {},
                characterRelationships: {},
              },
            },
            currentWorldId: seed.world.id,
            currentEntityId: seed.world.id,
            error: null,
            loading: false,
          },
          version: 2,
        } as const;

        const npcEntries = Object.fromEntries(
          seed.npcs.map((npc) => [
            npc.id,
            {
              id: npc.id,
              name: npc.name,
              description: npc.description,
              worldId: seed.world.id,
              avatarUrl: npc.avatarUrl,
              createdAt: now,
              updatedAt: now,
            },
          ])
        );

        const npcPersist = {
          state: {
            npcs: npcEntries,
            entities: npcEntries,
            worldNpcs: {
              [seed.world.id]: seed.npcs.map((n) => n.id),
            },
            currentEntityId: null,
            error: null,
            loading: false,
          },
          version: 2,
        } as const;

        await Promise.all([
          put('narraitor-world-store', worldPersist),
          put('narraitor-npc-store', npcPersist),
        ]);
      },
      { now: SEEDED_AT, seed: SEED_PAYLOAD }
    );

    await page.goto(`${baseURL}/worlds/${WORLD_ID}`, {
      waitUntil: 'domcontentloaded',
    });

    // Wait for the NPC section heading
    await page.waitForSelector('text=NPCs', { timeout: 10000 });

    // Wait for NPCs to be visible
    await expect(page.locator('text=Elara Moonwhisper')).toBeVisible({
      timeout: 10000,
    });
    await expect(page.locator('text=Thorgrim Ironforge')).toBeVisible({
      timeout: 10000,
    });

    // Verify NPC with portrait shows avatar image
    const elaraAvatar = page.locator('img[alt="Elara Moonwhisper"]');
    await expect(elaraAvatar).toBeVisible();

    // Verify NPC without portrait shows initials fallback
    // The initials should be "TI" for Thorgrim Ironforge
    const thorInitials = page.locator('text=TI').first();
    await expect(thorInitials).toBeVisible();

    await expect(page).toHaveScreenshot('world-details-npc-portraits.png', {
      animations: 'disabled',
      fullPage: true,
    });
  });
});
