import type { Meta, StoryObj } from '@storybook/react';
import { WorldSkillsList } from './WorldSkillsList';
import { WorldSkill, WorldAttribute } from '@/types/world.types';

const meta = {
  title: 'Narraitor/World/Display/WorldSkillsList',
  component: WorldSkillsList,
  parameters: {
    layout: 'padded',
  },
  tags: ['autodocs'],
} satisfies Meta<typeof WorldSkillsList>;

export default meta;
type Story = StoryObj<typeof meta>;

// Mock attributes for linking
const mockAttributes: WorldAttribute[] = [
  {
    id: 'str',
    worldId: 'world-test',
    name: 'Strength',
    description: 'Physical power',
    minValue: 1,
    maxValue: 20,
    baseValue: 10,
    category: 'Physical',
  },
  {
    id: 'dex',
    worldId: 'world-test',
    name: 'Dexterity',
    description: 'Agility',
    minValue: 1,
    maxValue: 20,
    baseValue: 10,
    category: 'Physical',
  },
  {
    id: 'int',
    worldId: 'world-test',
    name: 'Intelligence',
    description: 'Mental acuity',
    minValue: 1,
    maxValue: 20,
    baseValue: 10,
    category: 'Mental',
  },
  {
    id: 'wis',
    worldId: 'world-test',
    name: 'Wisdom',
    description: 'Awareness',
    minValue: 1,
    maxValue: 20,
    baseValue: 10,
    category: 'Mental',
  },
];

// Mock skills
const mockSkills: WorldSkill[] = [
  {
    id: 'swordsmanship',
    worldId: 'world-test',
    name: 'Swordsmanship',
    description: 'The art of fighting with bladed weapons',
    linkedAttributeId: 'str',
    difficulty: 'medium',
    category: 'Combat',
    minValue: 1,
    maxValue: 20,
    baseValue: 5,
  },
  {
    id: 'stealth',
    worldId: 'world-test',
    name: 'Stealth',
    description: 'The ability to move unseen and unheard',
    linkedAttributeId: 'dex',
    difficulty: 'hard',
    category: 'Utility',
    minValue: 1,
    maxValue: 20,
    baseValue: 3,
  },
  {
    id: 'lore',
    worldId: 'world-test',
    name: 'Lore',
    description: 'Knowledge of history, magic, and ancient secrets',
    linkedAttributeId: 'int',
    difficulty: 'easy',
    category: 'Knowledge',
    minValue: 1,
    maxValue: 20,
    baseValue: 7,
  },
  {
    id: 'perception',
    worldId: 'world-test',
    name: 'Perception',
    description: 'Noticing details and hidden things',
    linkedAttributeId: 'wis',
    difficulty: 'medium',
    category: 'Utility',
    minValue: 1,
    maxValue: 20,
    baseValue: 5,
  },
];

export const Default: Story = {
  args: {
    skills: mockSkills,
    attributes: mockAttributes,
  },
};

export const MinimalSkills: Story = {
  args: {
    skills: [
      {
        id: 'combat',
        worldId: 'world-test',
        name: 'Combat',
        description: 'Fighting ability',
        linkedAttributeId: 'str',
        difficulty: 'medium',
        category: 'Combat',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
      {
        id: 'magic',
        worldId: 'world-test',
        name: 'Magic',
        description: 'Spellcasting ability',
        linkedAttributeId: 'int',
        difficulty: 'hard',
        category: 'Mystical',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
    ],
    attributes: mockAttributes,
  },
};

export const WithoutDescriptions: Story = {
  args: {
    skills: [
      {
        id: 'swordsmanship',
        worldId: 'world-test',
        name: 'Swordsmanship',
        description: '',
        linkedAttributeId: 'str',
        difficulty: 'medium',
        category: 'Combat',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
      {
        id: 'stealth',
        worldId: 'world-test',
        name: 'Stealth',
        description: '',
        linkedAttributeId: 'dex',
        difficulty: 'hard',
        category: 'Utility',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
    ],
    attributes: mockAttributes,
  },
};

export const WithoutLinkedAttributes: Story = {
  args: {
    skills: [
      {
        id: 'leadership',
        worldId: 'world-test',
        name: 'Leadership',
        description: 'Ability to inspire and command others',
        difficulty: 'hard',
        category: 'Social',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
      {
        id: 'survival',
        worldId: 'world-test',
        name: 'Survival',
        description: 'Living off the land and in harsh conditions',
        difficulty: 'medium',
        category: 'Utility',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
    ],
    attributes: mockAttributes,
  },
};

export const Fantasy: Story = {
  args: {
    skills: [
      {
        id: 'swordsmanship',
        worldId: 'world-test',
        name: 'Swordsmanship',
        description: 'Mastery of blade combat and weapon techniques',
        linkedAttributeId: 'str',
        difficulty: 'medium',
        category: 'Combat',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
      {
        id: 'archery',
        worldId: 'world-test',
        name: 'Archery',
        description: 'Precision shooting with bow and arrow',
        linkedAttributeId: 'dex',
        difficulty: 'medium',
        category: 'Combat',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
      {
        id: 'magic',
        worldId: 'world-test',
        name: 'Arcane Magic',
        description: 'Manipulation of mystical forces and spellcasting',
        linkedAttributeId: 'int',
        difficulty: 'hard',
        category: 'Mystical',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
      {
        id: 'divine_magic',
        worldId: 'world-test',
        name: 'Divine Magic',
        description: 'Channeling divine power for healing and protection',
        linkedAttributeId: 'wis',
        difficulty: 'hard',
        category: 'Mystical',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
      {
        id: 'stealth',
        worldId: 'world-test',
        name: 'Stealth',
        description: 'Moving silently and remaining hidden',
        linkedAttributeId: 'dex',
        difficulty: 'hard',
        category: 'Utility',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
      {
        id: 'lore',
        worldId: 'world-test',
        name: 'Ancient Lore',
        description: 'Knowledge of history, legends, and forgotten secrets',
        linkedAttributeId: 'int',
        difficulty: 'medium',
        category: 'Knowledge',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
    ],
    attributes: mockAttributes,
  },
};

export const SciFi: Story = {
  args: {
    skills: [
      {
        id: 'piloting',
        worldId: 'world-test',
        name: 'Spacecraft Piloting',
        description: 'Operating various types of spacecraft and vehicles',
        linkedAttributeId: 'dex',
        difficulty: 'hard',
        category: 'Technical',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
      {
        id: 'hacking',
        worldId: 'world-test',
        name: 'System Hacking',
        description: 'Breaking into computer systems and networks',
        linkedAttributeId: 'int',
        difficulty: 'hard',
        category: 'Technical',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
      {
        id: 'cybercombat',
        worldId: 'world-test',
        name: 'Cyber Combat',
        description: 'Fighting in virtual and augmented reality',
        linkedAttributeId: 'int',
        difficulty: 'hard',
        category: 'Combat',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
      {
        id: 'engineering',
        worldId: 'world-test',
        name: 'Engineering',
        description: 'Design and maintenance of advanced technology',
        linkedAttributeId: 'int',
        difficulty: 'medium',
        category: 'Technical',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
    ],
    attributes: [
      {
        id: 'body',
        worldId: 'world-test',
        name: 'Body',
        description: 'Physical conditioning',
        minValue: 1,
        maxValue: 10,
        baseValue: 5,
        category: 'Physical',
      },
      {
        id: 'mind',
        worldId: 'world-test',
        name: 'Mind',
        description: 'Neural processing',
        minValue: 1,
        maxValue: 10,
        baseValue: 5,
        category: 'Mental',
      },
      {
        id: 'tech',
        worldId: 'world-test',
        name: 'Tech',
        description: 'Technology integration',
        minValue: 1,
        maxValue: 10,
        baseValue: 5,
        category: 'Technical',
      },
    ],
  },
};

export const VariedDifficulties: Story = {
  args: {
    skills: [
      {
        id: 'walking',
        worldId: 'world-test',
        name: 'Walking',
        description: 'Basic movement on foot',
        linkedAttributeId: 'str',
        difficulty: 'easy',
        category: 'Basic',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
      {
        id: 'reading',
        worldId: 'world-test',
        name: 'Reading',
        description: 'Understanding written text',
        linkedAttributeId: 'int',
        difficulty: 'easy',
        category: 'Basic',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
      {
        id: 'cooking',
        worldId: 'world-test',
        name: 'Cooking',
        description: 'Preparing meals and food',
        linkedAttributeId: 'dex',
        difficulty: 'medium',
        category: 'Craft',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
      {
        id: 'surgery',
        worldId: 'world-test',
        name: 'Surgery',
        description: 'Advanced medical procedures',
        linkedAttributeId: 'dex',
        difficulty: 'hard',
        category: 'Medical',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
      {
        id: 'time_travel',
        worldId: 'world-test',
        name: 'Time Travel',
        description: 'Manipulating the flow of time itself',
        linkedAttributeId: 'int',
        difficulty: 'hard',
        category: 'Mystical',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
    ],
    attributes: mockAttributes,
  },
};

export const Empty: Story = {
  args: {
    skills: [],
    attributes: mockAttributes,
  },
};

export const SingleSkill: Story = {
  args: {
    skills: [
      {
        id: 'ultimate_power',
        worldId: 'world-test',
        name: 'Ultimate Power',
        description: 'The ability to do anything and everything with pure will',
        linkedAttributeId: 'wis',
        difficulty: 'hard',
        category: 'Divine',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
    ],
    attributes: mockAttributes,
  },
};

export const ManySkills: Story = {
  args: {
    skills: [
      {
        id: 'athletics',
        worldId: 'world-test',
        name: 'Athletics',
        description: 'Running, jumping, climbing',
        linkedAttributeId: 'str',
        difficulty: 'easy',
        category: 'Physical',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
      {
        id: 'acrobatics',
        worldId: 'world-test',
        name: 'Acrobatics',
        description: 'Balance and agility',
        linkedAttributeId: 'dex',
        difficulty: 'medium',
        category: 'Physical',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
      {
        id: 'investigation',
        worldId: 'world-test',
        name: 'Investigation',
        description: 'Finding clues and solving mysteries',
        linkedAttributeId: 'int',
        difficulty: 'medium',
        category: 'Mental',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
      {
        id: 'insight',
        worldId: 'world-test',
        name: 'Insight',
        description: 'Reading people and situations',
        linkedAttributeId: 'wis',
        difficulty: 'hard',
        category: 'Social',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
      {
        id: 'medicine',
        worldId: 'world-test',
        name: 'Medicine',
        description: 'Healing and medical knowledge',
        linkedAttributeId: 'wis',
        difficulty: 'medium',
        category: 'Knowledge',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
      {
        id: 'performance',
        worldId: 'world-test',
        name: 'Performance',
        description: 'Entertaining others',
        linkedAttributeId: 'str',
        difficulty: 'easy',
        category: 'Social',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
      {
        id: 'persuasion',
        worldId: 'world-test',
        name: 'Persuasion',
        description: 'Convincing others',
        linkedAttributeId: 'str',
        difficulty: 'medium',
        category: 'Social',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
      {
        id: 'sleight_of_hand',
        worldId: 'world-test',
        name: 'Sleight of Hand',
        description: 'Manual dexterity and tricks',
        linkedAttributeId: 'dex',
        difficulty: 'hard',
        category: 'Utility',
        minValue: 1,
        maxValue: 20,
        baseValue: 5,
      },
    ],
    attributes: mockAttributes,
  },
};
